### ISSUE TITLE
CUADRO COMPARATIVO ACTIVIDAD 3 

### ISSUE THREAD

**Issue by YaelTrinidad** [SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-YaelTrinidad#1]
[C.COMP_METODO_CIENTIFICO_YAEL.T.M.C.pdf](https://github.com/SistemasTecTlaxiaco/actividad-3-cuadro-comparativo-YaelTrinidad/files/9449574/C.COMP_METODO_CIENTIFICO_YAEL.T.M.C.pdf)

**Comment by Daniel-Velasco-Lopez** [comment]
El color obstruye para una mejor lectura,
De acuerdo a la rúbrica, has obtenido un 18.8% del 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
